# Generated by Django 5.2.17 on 2026-09-14 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seed_experiences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('award', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.CharField(blank=True, help_text='Image URL or local static path, for example /static/image/PKM.jpeg.', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title', 'id'],
            },
        ),
    ]
